
TOP_SRCDIR=../..

SRCS = cb_ar.c cb_erhd.c cb_inp.c cb_sedt.c cb_ws.c \
	cb_cell.c cb_err.c cb_nset.c cb_stru.c cb_xfut.c \
	cb_erfn.c cb_colr.c cb_fill.c cb_plin.c cb_text.c \
	cb_ctrl.c cb_pmrk.c cb_util.c cb_esc.c \
	cb_wst.c cb_mf.c cb_nurb.c cb_dcue.c cb_lite.c

include $(TOP_SRCDIR)/makeinclude
