
TOP_SRCDIR=../..

SRCS = ut_path.c ut_mat.c ut_misc.c utx.c utx_conv.c ut_ntfy.c \
       ut_htab.c

# libXaw ha degli undefined, si puo' utilizzare libXaw3d al suo posto
# ut_wchar.c

include $(TOP_SRCDIR)/makeinclude
