
TOP_SRCDIR=../..

SRCS = cp_util.c cp_ccom.c cp_rcom.c cp_inp.c psl.c \
	cpx_clnt.c cpx_util.c cpx_css.c cpx_ws.c cpx_ar.c cpx_misc.c cpx_pm.c \
	cpa_clnt.c cpa_util.c cpa_css.c cpa_ws.c cpa_pm.c \
	cpb_clnt.c cpb_util.c cpb_css.c cpb_ws.c cpb_pm.c \
	cpm_xevnt.c cpm_tlkt.c

include $(TOP_SRCDIR)/makeinclude
