#!/bin/sh

##
## $XConsortium: link_c_func.sh,v 1.3 94/04/17 20:54:08 hersh Exp $
##
## 
## Copyright (c) 1990, 1991 by Sun Microsystems, Inc. and the X Consortium.
## 
##                         All Rights Reserved
## 
## Permission to use, copy, modify, and distribute this software and its 
## documentation for any purpose and without fee is hereby granted, 
## provided that the above copyright notice appear in all copies and that
## both that copyright notice and this permission notice appear in 
## supporting documentation, and that the names of Sun Microsystems
## the X Consortium not be used in advertising or publicity 
## pertaining to distribution of the software without specific, written 
## prior permission.  
## 
## SUN MICROSYSTEMS DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, 
## INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
## EVENT SHALL SUN MICROSYSTEMS BE LIABLE FOR ANY SPECIAL, INDIRECT OR
## CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
## USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
## OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
## PERFORMANCE OF THIS SOFTWARE.

cd ${1}

if [ ! -d man3 ]
then
	\mkdir man3
fi
yes | \rm man3/* 2>/dev/null

ln -s ../manpages/p001 man3/padd_names_set.3
ln -s ../manpages/p002 man3/panno_text_rel.3
ln -s ../manpages/p003 man3/panno_text_rel3.3
ln -s ../manpages/p004 man3/pappl_data.3
ln -s ../manpages/p005 man3/par_all_structs.3
ln -s ../manpages/p006 man3/par_struct_nets.3
ln -s ../manpages/p007 man3/par_structs.3
ln -s ../manpages/p008 man3/pawait_event.3
ln -s ../manpages/p009 man3/pbuild_tran_matrix.3
ln -s ../manpages/p010 man3/pbuild_tran_matrix3.3
ln -s ../manpages/p011 man3/pcell_array.3
ln -s ../manpages/p012 man3/pcell_array3.3
ln -s ../manpages/p013 man3/pcell_array3_plus.3
ln -s ../manpages/p014 man3/pchange_struct_id.3
ln -s ../manpages/p015 man3/pchange_struct_id_refs.3
ln -s ../manpages/p016 man3/pchange_struct_refs.3
ln -s ../manpages/p017 man3/pclose_ar_file.3
ln -s ../manpages/p018 man3/pclose_phigs.3
ln -s ../manpages/p019 man3/pclose_struct.3
ln -s ../manpages/p020 man3/pclose_ws.3
ln -s ../manpages/p021 man3/pcompose_matrix.3
ln -s ../manpages/p022 man3/pcompose_matrix3.3
ln -s ../manpages/p023 man3/pcompose_tran_matrix.3
ln -s ../manpages/p024 man3/pcompose_tran_matrix3.3
ln -s ../manpages/p025 man3/pcomp_fill_area_set_gnorm.3
ln -s ../manpages/p026 man3/pcopy_all_elems_struct.3
ln -s ../manpages/p027 man3/pcreate_store.3
ln -s ../manpages/p028 man3/pdel_all_structs.3
ln -s ../manpages/p029 man3/pdel_all_structs_ar.3
ln -s ../manpages/p030 man3/pdel_elem.3
ln -s ../manpages/p031 man3/pdel_elem_range.3
ln -s ../manpages/p032 man3/pdel_elems_labels.3
ln -s ../manpages/p033 man3/pdel_store.3
ln -s ../manpages/p034 man3/pdel_struct.3
ln -s ../manpages/p035 man3/pdel_struct_net.3
ln -s ../manpages/p036 man3/pdel_struct_nets_ar.3
ln -s ../manpages/p037 man3/pdel_structs_ar.3
ln -s ../manpages/p038 man3/pelem_search.3
ln -s ../manpages/p039 man3/pemergency_close_phigs.3
ln -s ../manpages/p040 man3/pempty_struct.3
ln -s ../manpages/p041 man3/perr_hand.3
ln -s ../manpages/p042 man3/perr_log.3
ln -s ../manpages/p043 man3/pescape.3
ln -s ../manpages/p044 man3/pescape-1.3
ln -s ../manpages/p045 man3/pescape-2.3
ln -s ../manpages/p046 man3/pescape-3.3
ln -s ../manpages/p047 man3/pescape-4.3
ln -s ../manpages/p048 man3/pescape-5.3
ln -s ../manpages/p049 man3/pescape-6.3
ln -s ../manpages/p050 man3/pescape-7.3
ln -s ../manpages/p051 man3/peval_view_map_matrix.3
ln -s ../manpages/p052 man3/peval_view_map_matrix3.3
ln -s ../manpages/p053 man3/peval_view_ori_matrix.3
ln -s ../manpages/p054 man3/peval_view_ori_matrix3.3
ln -s ../manpages/p055 man3/pexec_struct.3
ln -s ../manpages/p056 man3/pfill_area.3
ln -s ../manpages/p057 man3/pfill_area3.3
ln -s ../manpages/p058 man3/pfill_area_set.3
ln -s ../manpages/p059 man3/pfill_area_set3.3
ln -s ../manpages/p060 man3/pfill_area_set3_data.3
ln -s ../manpages/p061 man3/pflush_events.3
ln -s ../manpages/p062 man3/pgdp.3
ln -s ../manpages/p063 man3/pgdp3.3
ln -s ../manpages/p064 man3/pgse.3
ln -s ../manpages/p065 man3/pget_choice.3
ln -s ../manpages/p066 man3/pget_loc.3
ln -s ../manpages/p067 man3/pget_loc3.3
ln -s ../manpages/p068 man3/pget_pick.3
ln -s ../manpages/p069 man3/pget_string.3
ln -s ../manpages/p070 man3/pget_stroke.3
ln -s ../manpages/p071 man3/pget_stroke3.3
ln -s ../manpages/p072 man3/pget_val.3
ln -s ../manpages/p073 man3/pincr_spa_search.3
ln -s ../manpages/p074 man3/pincr_spa_search3.3
ln -s ../manpages/p075 man3/pinit_choice.3
ln -s ../manpages/p076 man3/pinit_choice3.3
ln -s ../manpages/p077 man3/pinit_loc.3
ln -s ../manpages/p078 man3/pinit_loc3.3
ln -s ../manpages/p079 man3/pinit_pick.3
ln -s ../manpages/p080 man3/pinit_pick3.3
ln -s ../manpages/p081 man3/pinit_string.3
ln -s ../manpages/p082 man3/pinit_string3.3
ln -s ../manpages/p083 man3/pinit_stroke.3
ln -s ../manpages/p084 man3/pinit_stroke3.3
ln -s ../manpages/p085 man3/pinit_val.3
ln -s ../manpages/p086 man3/pinit_val3.3
ln -s ../manpages/p087 man3/pinq_all_conf_structs.3
ln -s ../manpages/p088 man3/pinq_anno_facs.3
ln -s ../manpages/p089 man3/pinq_ar_files.3
ln -s ../manpages/p090 man3/pinq_ar_st.3
ln -s ../manpages/p091 man3/pinq_choice_st.3
ln -s ../manpages/p092 man3/pinq_choice_st3.3
ln -s ../manpages/p093 man3/pinq_colr_facs.3
ln -s ../manpages/p094 man3/pinq_colr_map_facs.3
ln -s ../manpages/p095 man3/pinq_colr_map_method_facs.3
ln -s ../manpages/p096 man3/pinq_colr_map_rep.3
ln -s ../manpages/p097 man3/pinq_colr_map_st.3
ln -s ../manpages/p098 man3/pinq_colr_model.3
ln -s ../manpages/p099 man3/pinq_colr_model_facs.3
ln -s ../manpages/p100 man3/pinq_colr_rep.3
ln -s ../manpages/p101 man3/pinq_conf_res.3
ln -s ../manpages/p102 man3/pinq_conf_structs_net.3
ln -s ../manpages/p103 man3/pinq_cur_elem_content.3
ln -s ../manpages/p104 man3/pinq_cur_elem_type_size.3
ln -s ../manpages/p105 man3/pinq_curv_surf_facs.3
ln -s ../manpages/p106 man3/pinq_def_choice_data.3
ln -s ../manpages/p107 man3/pinq_def_choice_data3.3
ln -s ../manpages/p108 man3/pinq_def_disp_upd_st.3
ln -s ../manpages/p109 man3/pinq_def_loc_data.3
ln -s ../manpages/p110 man3/pinq_def_loc_data3.3
ln -s ../manpages/p111 man3/pinq_def_pick_data.3
ln -s ../manpages/p112 man3/pinq_def_pick_data3.3
ln -s ../manpages/p113 man3/pinq_def_string_data.3
ln -s ../manpages/p114 man3/pinq_def_string_data3.3
ln -s ../manpages/p115 man3/pinq_def_stroke_data.3
ln -s ../manpages/p116 man3/pinq_def_stroke_data3.3
ln -s ../manpages/p117 man3/pinq_def_val_data.3
ln -s ../manpages/p118 man3/pinq_def_val_data3.3
ln -s ../manpages/p119 man3/pinq_dcue_facs.3
ln -s ../manpages/p120 man3/pinq_dcue_rep.3
ln -s ../manpages/p121 man3/pinq_direct_colr_model_facs.3
ln -s ../manpages/p122 man3/pinq_disp_space_size.3
ln -s ../manpages/p123 man3/pinq_disp_space_size3.3
ln -s ../manpages/p124 man3/pinq_disp_upd_st.3
ln -s ../manpages/p125 man3/pinq_dyns_structs.3
ln -s ../manpages/p126 man3/pinq_dyns_ws_attrs.3
ln -s ../manpages/p127 man3/pinq_dyns_ws_attrs_plus.3
ln -s ../manpages/p128 man3/pinq_edge_facs.3
ln -s ../manpages/p129 man3/pinq_edge_rep.3
ln -s ../manpages/p130 man3/pinq_edge_rep_plus.3
ln -s ../manpages/p131 man3/pinq_edit_mode.3
ln -s ../manpages/p132 man3/pinq_elem_content.3
ln -s ../manpages/p133 man3/pinq_elem_ptr.3
ln -s ../manpages/p134 man3/pinq_elem_type_size.3
ln -s ../manpages/p135 man3/pinq_err_hand_mode.3
ln -s ../manpages/p136 man3/pinq_gdp.3
ln -s ../manpages/p137 man3/pinq_gdp3.3
ln -s ../manpages/p138 man3/pinq_gse_facs.3
ln -s ../manpages/p139 man3/pinq_highl_filter.3
ln -s ../manpages/p140 man3/pinq_hlhsr_id_facs.3
ln -s ../manpages/p141 man3/pinq_hlhsr_mode.3
ln -s ../manpages/p142 man3/pinq_hlhsr_mode_facs.3
ln -s ../manpages/p143 man3/pinq_in_overf.3
ln -s ../manpages/p144 man3/pinq_int_facs.3
ln -s ../manpages/p145 man3/pinq_int_facs_plus.3
ln -s ../manpages/p146 man3/pinq_int_rep.3
ln -s ../manpages/p147 man3/pinq_int_rep_plus.3
ln -s ../manpages/p148 man3/pinq_invis_filter.3
ln -s ../manpages/p149 man3/pinq_light_src_facs.3
ln -s ../manpages/p150 man3/pinq_light_src_rep.3
ln -s ../manpages/p151 man3/pinq_list_avail_gdp.3
ln -s ../manpages/p152 man3/pinq_list_avail_gdp3.3
ln -s ../manpages/p153 man3/pinq_list_avail_gse.3
ln -s ../manpages/p154 man3/pinq_list_avail_ws_types.3
ln -s ../manpages/p155 man3/pinq_list_colr_inds.3
ln -s ../manpages/p156 man3/pinq_list_colr_map_inds.3
ln -s ../manpages/p157 man3/pinq_list_dcue_inds.3
ln -s ../manpages/p158 man3/pinq_list_edge_inds.3
ln -s ../manpages/p159 man3/pinq_list_int_inds.3
ln -s ../manpages/p160 man3/pinq_list_light_src_inds.3
ln -s ../manpages/p161 man3/pinq_list_pat_inds.3
ln -s ../manpages/p162 man3/pinq_list_line_inds.3
ln -s ../manpages/p163 man3/pinq_list_marker_inds.3
ln -s ../manpages/p164 man3/pinq_list_text_inds.3
ln -s ../manpages/p165 man3/pinq_list_view_inds.3
ln -s ../manpages/p166 man3/pinq_loc_st.3
ln -s ../manpages/p167 man3/pinq_loc_st3.3
ln -s ../manpages/p168 man3/pinq_model_clip_facs.3
ln -s ../manpages/p169 man3/pinq_more_simult_events.3
ln -s ../manpages/p170 man3/pinq_num_avail_in.3
ln -s ../manpages/p171 man3/pinq_num_disp_pris.3
ln -s ../manpages/p172 man3/pinq_open_struct.3
ln -s ../manpages/p173 man3/pinq_paths_ances.3
ln -s ../manpages/p174 man3/pinq_paths_descs.3
ln -s ../manpages/p175 man3/pinq_pat_facs.3
ln -s ../manpages/p176 man3/pinq_pat_rep.3
ln -s ../manpages/p177 man3/pinq_pat_rep_plus.3
ln -s ../manpages/p178 man3/pinq_phigs_facs.3
ln -s ../manpages/p179 man3/pinq_pick_st.3
ln -s ../manpages/p180 man3/pinq_pick_st3.3
ln -s ../manpages/p181 man3/pinq_line_facs.3
ln -s ../manpages/p182 man3/pinq_line_facs_plus.3
ln -s ../manpages/p183 man3/pinq_line_rep.3
ln -s ../manpages/p184 man3/pinq_line_rep_plus.3
ln -s ../manpages/p185 man3/pinq_marker_facs.3
ln -s ../manpages/p186 man3/pinq_marker_rep.3
ln -s ../manpages/p187 man3/pinq_marker_rep_plus.3
ln -s ../manpages/p188 man3/pinq_posted_structs.3
ln -s ../manpages/p189 man3/pinq_pred_colr_map_rep.3
ln -s ../manpages/p190 man3/pinq_pred_colr_rep.3
ln -s ../manpages/p191 man3/pinq_pred_dcue_rep.3
ln -s ../manpages/p192 man3/pinq_pred_edge_rep.3
ln -s ../manpages/p193 man3/pinq_pred_edge_rep_plus.3
ln -s ../manpages/p194 man3/pinq_pred_int_rep.3
ln -s ../manpages/p195 man3/pinq_pred_int_rep_plus.3
ln -s ../manpages/p196 man3/pinq_pred_light_src_rep.3
ln -s ../manpages/p197 man3/pinq_pred_pat_rep.3
ln -s ../manpages/p198 man3/pinq_pred_pat_rep_plus.3
ln -s ../manpages/p199 man3/pinq_pred_line_rep.3
ln -s ../manpages/p200 man3/pinq_pred_line_rep_plus.3
ln -s ../manpages/p201 man3/pinq_pred_marker_rep.3
ln -s ../manpages/p202 man3/pinq_pred_marker_rep_plus.3
ln -s ../manpages/p203 man3/pinq_pred_text_rep.3
ln -s ../manpages/p204 man3/pinq_pred_text_rep_plus.3
ln -s ../manpages/p205 man3/pinq_pred_view_rep.3
ln -s ../manpages/p206 man3/pinq_rendering_colr_model_facs.3
ln -s ../manpages/p207 man3/pinq_open_wss.3
ln -s ../manpages/p208 man3/pinq_wss_posted.3
ln -s ../manpages/p209 man3/pinq_string_st.3
ln -s ../manpages/p210 man3/pinq_string_st3.3
ln -s ../manpages/p211 man3/pinq_stroke_st.3
ln -s ../manpages/p212 man3/pinq_stroke_st3.3
ln -s ../manpages/p213 man3/pinq_struct_ids.3
ln -s ../manpages/p214 man3/pinq_struct_st.3
ln -s ../manpages/p215 man3/pinq_struct_status.3
ln -s ../manpages/p216 man3/pinq_sys_st.3
ln -s ../manpages/p217 man3/pinq_text_extent.3
ln -s ../manpages/p218 man3/pinq_text_facs.3
ln -s ../manpages/p219 man3/pinq_text_rep.3
ln -s ../manpages/p220 man3/pinq_text_rep_plus.3
ln -s ../manpages/p221 man3/pinq_val_st.3
ln -s ../manpages/p222 man3/pinq_val_st3.3
ln -s ../manpages/p223 man3/pinq_view_facs.3
ln -s ../manpages/p224 man3/pinq_view_rep.3
ln -s ../manpages/p225 man3/pinq_ws_cat.3
ln -s ../manpages/p226 man3/pinq_ws_class.3
ln -s ../manpages/p227 man3/pinq_ws_conn_type.3
ln -s ../manpages/p228 man3/pinq_ws_st_table.3
ln -s ../manpages/p229 man3/pinq_ws_st_table_plus.3
ln -s ../manpages/p230 man3/pinq_ws_st.3
ln -s ../manpages/p231 man3/pinq_ws_tran.3
ln -s ../manpages/p232 man3/pinq_ws_tran3.3
ln -s ../manpages/p233 man3/that.3
ln -s ../manpages/p234 man3/plabel.3
ln -s ../manpages/p235 man3/pmessage.3
ln -s ../manpages/p236 man3/pnuni_bsp_curv.3
ln -s ../manpages/p237 man3/pnuni_bsp_surf.3
ln -s ../manpages/p238 man3/poffset_elem_ptr.3
ln -s ../manpages/p239 man3/popen_ar_file.3
ln -s ../manpages/p240 man3/popen_phigs.3
ln -s ../manpages/p241 man3/popen_struct.3
ln -s ../manpages/p242 man3/popen_ws.3
ln -s ../manpages/p243 man3/popen_xphigs.3
ln -s ../manpages/p244 man3/ppolyline.3
ln -s ../manpages/p245 man3/ppolyline3.3
ln -s ../manpages/p246 man3/ppolyline_set3_data.3
ln -s ../manpages/p247 man3/ppolymarker.3
ln -s ../manpages/p248 man3/ppolymarker3.3
ln -s ../manpages/p249 man3/ppost_struct.3
ln -s ../manpages/p250 man3/pquad_mesh3_data.3
ln -s ../manpages/p251 man3/predraw_all_structs.3
ln -s ../manpages/p252 man3/premove_names_set.3
ln -s ../manpages/p253 man3/preq_choice.3
ln -s ../manpages/p254 man3/preq_loc.3
ln -s ../manpages/p255 man3/preq_loc3.3
ln -s ../manpages/p256 man3/preq_pick.3
ln -s ../manpages/p257 man3/preq_string.3
ln -s ../manpages/p258 man3/preq_stroke.3
ln -s ../manpages/p259 man3/preq_stroke3.3
ln -s ../manpages/p260 man3/preq_val.3
ln -s ../manpages/p261 man3/prestore_model_clip_vol.3
ln -s ../manpages/p262 man3/pret_all_structs.3
ln -s ../manpages/p263 man3/pret_paths_ances.3
ln -s ../manpages/p264 man3/pret_paths_descs.3
ln -s ../manpages/p265 man3/pret_struct_ids.3
ln -s ../manpages/p266 man3/pret_struct_nets.3
ln -s ../manpages/p267 man3/pret_structs.3
ln -s ../manpages/p268 man3/protate.3
ln -s ../manpages/p269 man3/protate_x.3
ln -s ../manpages/p270 man3/protate_y.3
ln -s ../manpages/p271 man3/protate_z.3
ln -s ../manpages/p272 man3/psample_choice.3
ln -s ../manpages/p273 man3/psample_loc.3
ln -s ../manpages/p274 man3/psample_loc3.3
ln -s ../manpages/p275 man3/psample_pick.3
ln -s ../manpages/p276 man3/psample_string.3
ln -s ../manpages/p277 man3/psample_stroke.3
ln -s ../manpages/p278 man3/psample_stroke3.3
ln -s ../manpages/p279 man3/psample_val.3
ln -s ../manpages/p280 man3/pscale.3
ln -s ../manpages/p281 man3/pscale3.3
ln -s ../manpages/p282 man3/pset_anno_style.3
ln -s ../manpages/p283 man3/pset_anno_align.3
ln -s ../manpages/p284 man3/pset_anno_char_ht.3
ln -s ../manpages/p285 man3/pset_anno_char_up_vec.3
ln -s ../manpages/p286 man3/pset_anno_path.3
ln -s ../manpages/p287 man3/pset_back_int_colr.3
ln -s ../manpages/p288 man3/pset_back_refl_eqn.3
ln -s ../manpages/p289 man3/pset_back_int_shade_meth.3
ln -s ../manpages/p290 man3/pset_back_int_style.3
ln -s ../manpages/p291 man3/pset_back_int_style_ind.3
ln -s ../manpages/p292 man3/pset_back_refl_props.3
ln -s ../manpages/p293 man3/pset_char_expan.3
ln -s ../manpages/p294 man3/pset_char_ht.3
ln -s ../manpages/p295 man3/pset_char_space.3
ln -s ../manpages/p296 man3/pset_char_up_vec.3
ln -s ../manpages/p297 man3/pset_choice_mode.3
ln -s ../manpages/p298 man3/pset_colr_map_ind.3
ln -s ../manpages/p299 man3/pset_colr_map_rep.3
ln -s ../manpages/p300 man3/pset_colr_model.3
ln -s ../manpages/p301 man3/pset_colr_rep.3
ln -s ../manpages/p302 man3/pset_conf_res.3
ln -s ../manpages/p303 man3/pset_curve_approx.3
ln -s ../manpages/p304 man3/pset_dcue_ind.3
ln -s ../manpages/p305 man3/pset_dcue_rep.3
ln -s ../manpages/p306 man3/pset_disp_upd_st.3
ln -s ../manpages/p307 man3/pset_edge_colr.3
ln -s ../manpages/p308 man3/pset_edge_colr_ind.3
ln -s ../manpages/p309 man3/pset_edge_flag.3
ln -s ../manpages/p310 man3/pset_edge_ind.3
ln -s ../manpages/p311 man3/pset_edge_rep.3
ln -s ../manpages/p312 man3/pset_edge_rep_plus.3
ln -s ../manpages/p313 man3/pset_edgetype.3
ln -s ../manpages/p314 man3/pset_edgewidth.3
ln -s ../manpages/p315 man3/pset_edit_mode.3
ln -s ../manpages/p316 man3/pset_elem_ptr.3
ln -s ../manpages/p317 man3/pset_elem_ptr_label.3
ln -s ../manpages/p318 man3/pset_err_hand.3
ln -s ../manpages/p319 man3/pset_err_hand_mode.3
ln -s ../manpages/p320 man3/pset_face_cull_mode.3
ln -s ../manpages/p321 man3/pset_face_disting_mode.3
ln -s ../manpages/p322 man3/pset_global_tran.3
ln -s ../manpages/p323 man3/pset_global_tran3.3
ln -s ../manpages/p324 man3/pset_highl_filter.3
ln -s ../manpages/p325 man3/pset_hlhsr_id.3
ln -s ../manpages/p326 man3/pset_hlhsr_mode.3
ln -s ../manpages/p327 man3/pset_indiv_asf.3
ln -s ../manpages/p328 man3/pset_int_colr.3
ln -s ../manpages/p329 man3/pset_int_colr_ind.3
ln -s ../manpages/p330 man3/pset_int_ind.3
ln -s ../manpages/p331 man3/pset_int_rep.3
ln -s ../manpages/p332 man3/pset_int_rep_plus.3
ln -s ../manpages/p333 man3/pset_int_shad_meth.3
ln -s ../manpages/p334 man3/pset_int_style.3
ln -s ../manpages/p335 man3/pset_int_style_ind.3
ln -s ../manpages/p336 man3/pset_invis_filter.3
ln -s ../manpages/p337 man3/pset_light_src_rep.3
ln -s ../manpages/p338 man3/pset_light_src_state.3
ln -s ../manpages/p339 man3/pset_linetype.3
ln -s ../manpages/p340 man3/pset_linewidth.3
ln -s ../manpages/p341 man3/pset_local_tran.3
ln -s ../manpages/p342 man3/pset_local_tran3.3
ln -s ../manpages/p343 man3/pset_loc_mode.3
ln -s ../manpages/p344 man3/pset_marker_size.3
ln -s ../manpages/p345 man3/pset_marker_type.3
ln -s ../manpages/p346 man3/pset_model_clip_ind.3
ln -s ../manpages/p347 man3/pset_model_clip_vol.3
ln -s ../manpages/p348 man3/pset_model_clip_vol3.3
ln -s ../manpages/p349 man3/pset_of_fill_area_set3_data.3
ln -s ../manpages/p350 man3/pset_para_surf_characs.3
ln -s ../manpages/p351 man3/pset_pat_ref_point.3
ln -s ../manpages/p352 man3/pset_pat_ref_point_vecs.3
ln -s ../manpages/p353 man3/pset_pat_rep.3
ln -s ../manpages/p354 man3/pset_pat_rep_plus.3
ln -s ../manpages/p355 man3/pset_pat_size.3
ln -s ../manpages/p356 man3/pset_pick_filter.3
ln -s ../manpages/p357 man3/pset_pick_id.3
ln -s ../manpages/p358 man3/pset_pick_mode.3
ln -s ../manpages/p359 man3/pset_line_colr.3
ln -s ../manpages/p360 man3/pset_line_colr_ind.3
ln -s ../manpages/p361 man3/pset_line_ind.3
ln -s ../manpages/p362 man3/pset_line_rep.3
ln -s ../manpages/p363 man3/pset_line_rep_plus.3
ln -s ../manpages/p364 man3/pset_line_shad_meth.3
ln -s ../manpages/p365 man3/pset_marker_colr.3
ln -s ../manpages/p366 man3/pset_marker_colr_ind.3
ln -s ../manpages/p367 man3/pset_marker_ind.3
ln -s ../manpages/p368 man3/pset_marker_rep.3
ln -s ../manpages/p369 man3/pset_marker_rep_plus.3
ln -s ../manpages/p370 man3/pset_refl_eqn.3
ln -s ../manpages/p371 man3/pset_refl_props.3
ln -s ../manpages/p372 man3/pset_rendering_colr_model.3
ln -s ../manpages/p373 man3/pset_string_mode.3
ln -s ../manpages/p374 man3/pset_stroke_mode.3
ln -s ../manpages/p375 man3/pset_surf_approx.3
ln -s ../manpages/p376 man3/pset_text_align.3
ln -s ../manpages/p377 man3/pset_text_colr.3
ln -s ../manpages/p378 man3/pset_text_colr_ind.3
ln -s ../manpages/p379 man3/pset_text_font.3
ln -s ../manpages/p380 man3/pset_text_ind.3
ln -s ../manpages/p381 man3/pset_text_path.3
ln -s ../manpages/p382 man3/pset_text_prec.3
ln -s ../manpages/p383 man3/pset_text_rep.3
ln -s ../manpages/p384 man3/pset_text_rep_plus.3
ln -s ../manpages/p385 man3/pset_val_mode.3
ln -s ../manpages/p386 man3/pset_view_ind.3
ln -s ../manpages/p387 man3/pset_view_rep.3
ln -s ../manpages/p388 man3/pset_view_rep3.3
ln -s ../manpages/p389 man3/pset_view_tran_in_pri.3
ln -s ../manpages/p390 man3/pset_ws_vp.3
ln -s ../manpages/p391 man3/pset_ws_vp3.3
ln -s ../manpages/p392 man3/pset_ws_win.3
ln -s ../manpages/p393 man3/pset_ws_win3.3
ln -s ../manpages/p394 man3/ptext.3
ln -s ../manpages/p395 man3/ptext3.3
ln -s ../manpages/p396 man3/ptran_point.3
ln -s ../manpages/p397 man3/ptran_point3.3
ln -s ../manpages/p398 man3/ptranslate.3
ln -s ../manpages/p399 man3/ptranslate3.3
ln -s ../manpages/p400 man3/ptri_strip3_data.3
ln -s ../manpages/p401 man3/punpost_all_structs.3
ln -s ../manpages/p402 man3/punpost_struct.3
ln -s ../manpages/p403 man3/pupd_ws.3
ln -s ../manpages/p404 man3/phigs_ws_type_create.3
ln -s ../manpages/p405 man3/phigs_ws_type_destroy.3
ln -s ../manpages/p406 man3/phigs_ws_type_get.3
ln -s ../manpages/p407 man3/phigs_ws_type_set.3

ln -s ../manpages/p001 man3/add_names_to_set.3
ln -s ../manpages/p002 man3/annotation_text_relative.3
ln -s ../manpages/p003 man3/annotation_text_relative_3.3
ln -s ../manpages/p004 man3/application_data.3
ln -s ../manpages/p005 man3/archive_all_structures.3
ln -s ../manpages/p006 man3/archive_structure_networks.3
ln -s ../manpages/p007 man3/archive_structures.3
ln -s ../manpages/p008 man3/await_event.3
ln -s ../manpages/p009 man3/build_transformation_matrix.3
ln -s ../manpages/p010 man3/build_transformation_matrix_3.3
ln -s ../manpages/p011 man3/cell_array.3
ln -s ../manpages/p012 man3/cell_array_3.3
ln -s ../manpages/p013 man3/cell_array_3_plus.3
ln -s ../manpages/p014 man3/change_structure_identifier.3
ln -s ../manpages/p015 man3/change_structure_identifier_and_references.3
ln -s ../manpages/p016 man3/change_structure_references.3
ln -s ../manpages/p017 man3/close_archive_file.3
ln -s ../manpages/p018 man3/close_phigs.3
ln -s ../manpages/p019 man3/close_structure.3
ln -s ../manpages/p020 man3/close_workstation.3
ln -s ../manpages/p021 man3/compose_matrix.3
ln -s ../manpages/p022 man3/compose_matrix_3.3
ln -s ../manpages/p023 man3/compose_transformation_matrix.3
ln -s ../manpages/p024 man3/compose_transformation_matrix_3.3
ln -s ../manpages/p025 man3/compute_fill_area_set_geometric_normal.3
ln -s ../manpages/p026 man3/copy_all_elements_from_structure.3
ln -s ../manpages/p027 man3/create_store.3
ln -s ../manpages/p028 man3/delete_all_structures.3
ln -s ../manpages/p029 man3/delete_all_structures_from_archive.3
ln -s ../manpages/p030 man3/delete_element.3
ln -s ../manpages/p031 man3/delete_element_range.3
ln -s ../manpages/p032 man3/delete_elements_between_labels.3
ln -s ../manpages/p033 man3/delete_store.3
ln -s ../manpages/p034 man3/delete_structure.3
ln -s ../manpages/p035 man3/delete_structure_network.3
ln -s ../manpages/p036 man3/delete_structure_networks_from_archive.3
ln -s ../manpages/p037 man3/delete_structures_from_archive.3
ln -s ../manpages/p038 man3/element_search.3
ln -s ../manpages/p039 man3/emergency_close_phigs.3
ln -s ../manpages/p040 man3/empty_structure.3
ln -s ../manpages/p041 man3/error_handling.3
ln -s ../manpages/p042 man3/error_logging.3
ln -s ../manpages/p043 man3/escape.3
ln -s ../manpages/p044 man3/escape_-1.3
ln -s ../manpages/p045 man3/escape_-2.3
ln -s ../manpages/p046 man3/escape_-3.3
ln -s ../manpages/p047 man3/escape_-4.3
ln -s ../manpages/p048 man3/escape_-5.3
ln -s ../manpages/p049 man3/escape_-6.3
ln -s ../manpages/p050 man3/escape_-7.3
ln -s ../manpages/p051 man3/evaluate_view_mapping_matrix.3
ln -s ../manpages/p052 man3/evaluate_view_mapping_matrix_3.3
ln -s ../manpages/p053 man3/evaluate_view_orientation_matrix.3
ln -s ../manpages/p054 man3/evaluate_view_orientation_matrix_3.3
ln -s ../manpages/p055 man3/execute_structure.3
ln -s ../manpages/p056 man3/fill_area.3
ln -s ../manpages/p057 man3/fill_area_3.3
ln -s ../manpages/p058 man3/fill_area_set.3
ln -s ../manpages/p059 man3/fill_area_set_3.3
ln -s ../manpages/p060 man3/fill_area_set_3_with_data.3
ln -s ../manpages/p061 man3/flush_device_events.3
ln -s ../manpages/p062 man3/generalized_drawing_primitive.3
ln -s ../manpages/p063 man3/generalized_drawing_primitive_3.3
ln -s ../manpages/p064 man3/generalized_structure_element.3
ln -s ../manpages/p065 man3/get_choice.3
ln -s ../manpages/p066 man3/get_locator.3
ln -s ../manpages/p067 man3/get_locator_3.3
ln -s ../manpages/p068 man3/get_pick.3
ln -s ../manpages/p069 man3/get_string.3
ln -s ../manpages/p070 man3/get_stroke.3
ln -s ../manpages/p071 man3/get_stroke_3.3
ln -s ../manpages/p072 man3/get_valuator.3
ln -s ../manpages/p073 man3/incremental_spatial_search.3
ln -s ../manpages/p074 man3/incremental_spatial_search_3.3
ln -s ../manpages/p075 man3/initialize_choice.3
ln -s ../manpages/p076 man3/initialize_choice_3.3
ln -s ../manpages/p077 man3/initialize_locator.3
ln -s ../manpages/p078 man3/initialize_locator_3.3
ln -s ../manpages/p079 man3/initialize_pick.3
ln -s ../manpages/p080 man3/initialize_pick_3.3
ln -s ../manpages/p081 man3/initialize_string.3
ln -s ../manpages/p082 man3/initialize_string_3.3
ln -s ../manpages/p083 man3/initialize_stroke.3
ln -s ../manpages/p084 man3/initialize_stroke_3.3
ln -s ../manpages/p085 man3/initialize_valuator.3
ln -s ../manpages/p086 man3/initialize_valuator_3.3
ln -s ../manpages/p087 man3/inquire_all_conflicting_structures.3
ln -s ../manpages/p088 man3/inquire_annotation_facilities.3
ln -s ../manpages/p089 man3/inquire_archive_files.3
ln -s ../manpages/p090 man3/inquire_archive_state_value.3
ln -s ../manpages/p091 man3/inquire_choice_device_state.3
ln -s ../manpages/p092 man3/inquire_choice_device_state_3.3
ln -s ../manpages/p093 man3/inquire_colour_facilities.3
ln -s ../manpages/p094 man3/inquire_colour_mapping_facilities.3
ln -s ../manpages/p095 man3/inquire_colour_mapping_method_facilities.3
ln -s ../manpages/p096 man3/inquire_colour_mapping_representation.3
ln -s ../manpages/p097 man3/inquire_colour_mapping_state.3
ln -s ../manpages/p098 man3/inquire_colour_model.3
ln -s ../manpages/p099 man3/inquire_colour_model_facilities.3
ln -s ../manpages/p100 man3/inquire_colour_representation.3
ln -s ../manpages/p101 man3/inquire_conflict_resolution.3
ln -s ../manpages/p102 man3/inquire_conflicting_structures_in_network.3
ln -s ../manpages/p103 man3/inquire_current_element_content.3
ln -s ../manpages/p104 man3/inquire_current_element_type_and_size.3
ln -s ../manpages/p105 man3/inquire_curve_and_surface_facilities.3
ln -s ../manpages/p106 man3/inquire_default_choice_device_data.3
ln -s ../manpages/p107 man3/inquire_default_choice_device_data_3.3
ln -s ../manpages/p108 man3/inquire_default_display_update_state.3
ln -s ../manpages/p109 man3/inquire_default_locator_device_data.3
ln -s ../manpages/p110 man3/inquire_default_locator_device_data_3.3
ln -s ../manpages/p111 man3/inquire_default_pick_device_data.3
ln -s ../manpages/p112 man3/inquire_default_pick_device_data_3.3
ln -s ../manpages/p113 man3/inquire_default_string_device_data.3
ln -s ../manpages/p114 man3/inquire_default_string_device_data_3.3
ln -s ../manpages/p115 man3/inquire_default_stroke_device_data.3
ln -s ../manpages/p116 man3/inquire_default_stroke_device_data_3.3
ln -s ../manpages/p117 man3/inquire_default_valuator_device_data.3
ln -s ../manpages/p118 man3/inquire_default_valuator_device_data_3.3
ln -s ../manpages/p119 man3/inquire_depth_cue_facilities.3
ln -s ../manpages/p120 man3/inquire_depth_cue_representation.3
ln -s ../manpages/p121 man3/inquire_direct_colour_model_facilities.3
ln -s ../manpages/p122 man3/inquire_display_space_size.3
ln -s ../manpages/p123 man3/inquire_display_space_size_3.3
ln -s ../manpages/p124 man3/inquire_display_update_state.3
ln -s ../manpages/p125 man3/inquire_dynamics_of_structures.3
ln -s ../manpages/p126 man3/inquire_dynamics_of_workstation_attributes.3
ln -s ../manpages/p127 man3/inquire_dynamics_of_workstation_plus.3
ln -s ../manpages/p128 man3/inquire_edge_facilities.3
ln -s ../manpages/p129 man3/inquire_edge_representation.3
ln -s ../manpages/p130 man3/inquire_edge_representation_plus.3
ln -s ../manpages/p131 man3/inquire_edit_mode.3
ln -s ../manpages/p132 man3/inquire_element_content.3
ln -s ../manpages/p133 man3/inquire_element_pointer.3
ln -s ../manpages/p134 man3/inquire_element_type_and_size.3
ln -s ../manpages/p135 man3/inquire_error_handling_mode.3
ln -s ../manpages/p136 man3/inquire_generalized_drawing_primitive.3
ln -s ../manpages/p137 man3/inquire_generalized_drawing_primitive_3.3
ln -s ../manpages/p138 man3/inquire_generalized_structure_element_facilities.3
ln -s ../manpages/p139 man3/inquire_highlighting_filter.3
ln -s ../manpages/p140 man3/inquire_hlhsr_identifier_facilities.3
ln -s ../manpages/p141 man3/inquire_hlhsr_mode.3
ln -s ../manpages/p142 man3/inquire_hlhsr_mode_facilities.3
ln -s ../manpages/p143 man3/inquire_input_queue_overflow.3
ln -s ../manpages/p144 man3/inquire_interior_facilities.3
ln -s ../manpages/p145 man3/inquire_interior_facilities_plus.3
ln -s ../manpages/p146 man3/inquire_interior_representation.3
ln -s ../manpages/p147 man3/inquire_interior_representation_plus.3
ln -s ../manpages/p148 man3/inquire_invisibility_filter.3
ln -s ../manpages/p149 man3/inquire_light_source_facilities.3
ln -s ../manpages/p150 man3/inquire_light_source_representation.3
ln -s ../manpages/p151 man3/inquire_list_of_available_generalized_drawing_primitives.3
ln -s ../manpages/p152 man3/inquire_list_of_available_generalized_drawing_primitives_3.3
ln -s ../manpages/p153 man3/inquire_list_of_available_generalized_structure_elements.3
ln -s ../manpages/p154 man3/inquire_list_of_available_workstation_types.3
ln -s ../manpages/p155 man3/inquire_list_of_colour_indices.3
ln -s ../manpages/p156 man3/inquire_list_of_colour_mapping_indices.3
ln -s ../manpages/p157 man3/inquire_list_of_depth_cue_indices.3
ln -s ../manpages/p158 man3/inquire_list_of_edge_indices.3
ln -s ../manpages/p159 man3/inquire_list_of_interior_indices.3
ln -s ../manpages/p160 man3/inquire_list_of_light_source_indices.3
ln -s ../manpages/p161 man3/inquire_list_of_pattern_indices.3
ln -s ../manpages/p162 man3/inquire_list_of_polyline_indices.3
ln -s ../manpages/p163 man3/inquire_list_of_polymarker_indices.3
ln -s ../manpages/p164 man3/inquire_list_of_text_indices.3
ln -s ../manpages/p165 man3/inquire_list_of_view_indices.3
ln -s ../manpages/p166 man3/inquire_locator_device_state.3
ln -s ../manpages/p167 man3/inquire_locator_device_state_3.3
ln -s ../manpages/p168 man3/inquire_modelling_clipping_facilities.3
ln -s ../manpages/p169 man3/inquire_more_simultaneous_events.3
ln -s ../manpages/p170 man3/inquire_number_of_available_logical_input_devices.3
ln -s ../manpages/p171 man3/inquire_number_of_display_priorities_supported.3
ln -s ../manpages/p172 man3/inquire_open_structure.3
ln -s ../manpages/p173 man3/inquire_paths_to_ancestors.3
ln -s ../manpages/p174 man3/inquire_paths_to_descendants.3
ln -s ../manpages/p175 man3/inquire_pattern_facilities.3
ln -s ../manpages/p176 man3/inquire_pattern_representation.3
ln -s ../manpages/p177 man3/inquire_pattern_representation_plus.3
ln -s ../manpages/p178 man3/inquire_phigs_facilities.3
ln -s ../manpages/p179 man3/inquire_pick_device_state.3
ln -s ../manpages/p180 man3/inquire_pick_device_state_3.3
ln -s ../manpages/p181 man3/inquire_polyline_facilities.3
ln -s ../manpages/p182 man3/inquire_polyline_facilities_plus.3
ln -s ../manpages/p183 man3/inquire_polyline_representation.3
ln -s ../manpages/p184 man3/inquire_polyline_representation_plus.3
ln -s ../manpages/p185 man3/inquire_polymarker_facilities.3
ln -s ../manpages/p186 man3/inquire_polymarker_representation.3
ln -s ../manpages/p187 man3/inquire_polymarker_representation_plus.3
ln -s ../manpages/p188 man3/inquire_posted_structures.3
ln -s ../manpages/p189 man3/inquire_predefined_colour_mapping_representation.3
ln -s ../manpages/p190 man3/inquire_predefined_colour_representation.3
ln -s ../manpages/p191 man3/inquire_predefined_depth_cue_representation.3
ln -s ../manpages/p192 man3/inquire_predefined_edge_representation.3
ln -s ../manpages/p193 man3/inquire_predefined_edge_representation_plus.3
ln -s ../manpages/p194 man3/inquire_predefined_interior_representation.3
ln -s ../manpages/p195 man3/inquire_predefined_interior_representation_plus.3
ln -s ../manpages/p196 man3/inquire_predefined_light_source_representation.3
ln -s ../manpages/p197 man3/inquire_predefined_pattern_representation.3
ln -s ../manpages/p198 man3/inquire_predefined_pattern_representation_plus.3
ln -s ../manpages/p199 man3/inquire_predefined_polyline_representation.3
ln -s ../manpages/p200 man3/inquire_predefined_polyline_representation_plus.3
ln -s ../manpages/p201 man3/inquire_predefined_polymarker_representation.3
ln -s ../manpages/p202 man3/inquire_predefined_polymarker_representation_plus.3
ln -s ../manpages/p203 man3/inquire_predefined_text_representation.3
ln -s ../manpages/p204 man3/inquire_predefined_text_representation_plus.3
ln -s ../manpages/p205 man3/inquire_predefined_view_representation.3
ln -s ../manpages/p206 man3/inquire_rendering_colour_model_facilities.3
ln -s ../manpages/p207 man3/inquire_set_of_open_workstations.3
ln -s ../manpages/p208 man3/inquire_set_of_workstations_to_which_posted.3
ln -s ../manpages/p209 man3/inquire_string_device_state.3
ln -s ../manpages/p210 man3/inquire_string_device_state_3.3
ln -s ../manpages/p211 man3/inquire_stroke_device_state.3
ln -s ../manpages/p212 man3/inquire_stroke_device_state_3.3
ln -s ../manpages/p213 man3/inquire_structure_identifiers.3
ln -s ../manpages/p214 man3/inquire_structure_state_value.3
ln -s ../manpages/p215 man3/inquire_structure_status.3
ln -s ../manpages/p216 man3/inquire_system_state_value.3
ln -s ../manpages/p217 man3/inquire_text_extent.3
ln -s ../manpages/p218 man3/inquire_text_facilities.3
ln -s ../manpages/p219 man3/inquire_text_representation.3
ln -s ../manpages/p220 man3/inquire_text_representation_plus.3
ln -s ../manpages/p221 man3/inquire_valuator_device_state.3
ln -s ../manpages/p222 man3/inquire_valuator_device_state_3.3
ln -s ../manpages/p223 man3/inquire_view_facilities.3
ln -s ../manpages/p224 man3/inquire_view_representation.3
ln -s ../manpages/p225 man3/inquire_workstation_category.3
ln -s ../manpages/p226 man3/inquire_workstation_classification.3
ln -s ../manpages/p227 man3/inquire_workstation_connection_and_type.3
ln -s ../manpages/p228 man3/inquire_workstation_state_table_lengths.3
ln -s ../manpages/p229 man3/inquire_workstation_state_table_lengths_plus.3
ln -s ../manpages/p230 man3/inquire_workstation_state_value.3
ln -s ../manpages/p231 man3/inquire_workstation_transformation.3
ln -s ../manpages/p232 man3/inquire_workstation_transformation_3.3
ln -s ../manpages/p233 man3/intro_phigs.3
ln -s ../manpages/p234 man3/label.3
ln -s ../manpages/p235 man3/message.3
ln -s ../manpages/p236 man3/non-uniform_b-spline_curve.3
ln -s ../manpages/p237 man3/non-uniform_b-spline_surface.3
ln -s ../manpages/p238 man3/offset_element_pointer.3
ln -s ../manpages/p239 man3/open_archive_file.3
ln -s ../manpages/p240 man3/open_phigs.3
ln -s ../manpages/p241 man3/open_structure.3
ln -s ../manpages/p242 man3/open_workstation.3
ln -s ../manpages/p243 man3/open_xphigs.3
ln -s ../manpages/p244 man3/polyline.3
ln -s ../manpages/p245 man3/polyline_3.3
ln -s ../manpages/p246 man3/polyline_set_3_with_data.3
ln -s ../manpages/p247 man3/polymarker.3
ln -s ../manpages/p248 man3/polymarker_3.3
ln -s ../manpages/p249 man3/post_structure.3
ln -s ../manpages/p250 man3/quadrilateral_mesh_3_with_data.3
ln -s ../manpages/p251 man3/redraw_all_structures.3
ln -s ../manpages/p252 man3/remove_names_from_set.3
ln -s ../manpages/p253 man3/request_choice.3
ln -s ../manpages/p254 man3/request_locator.3
ln -s ../manpages/p255 man3/request_locator_3.3
ln -s ../manpages/p256 man3/request_pick.3
ln -s ../manpages/p257 man3/request_string.3
ln -s ../manpages/p258 man3/request_stroke.3
ln -s ../manpages/p259 man3/request_stroke_3.3
ln -s ../manpages/p260 man3/request_valuator.3
ln -s ../manpages/p261 man3/restore_modelling_clipping_volume.3
ln -s ../manpages/p262 man3/retrieve_all_structures.3
ln -s ../manpages/p263 man3/retrieve_paths_to_ancestors.3
ln -s ../manpages/p264 man3/retrieve_paths_to_descendants.3
ln -s ../manpages/p265 man3/retrieve_structure_identifiers.3
ln -s ../manpages/p266 man3/retrieve_structure_networks.3
ln -s ../manpages/p267 man3/retrieve_structures.3
ln -s ../manpages/p268 man3/rotate.3
ln -s ../manpages/p269 man3/rotate_x.3
ln -s ../manpages/p270 man3/rotate_y.3
ln -s ../manpages/p271 man3/rotate_z.3
ln -s ../manpages/p272 man3/sample_choice.3
ln -s ../manpages/p273 man3/sample_locator.3
ln -s ../manpages/p274 man3/sample_locator_3.3
ln -s ../manpages/p275 man3/sample_pick.3
ln -s ../manpages/p276 man3/sample_string.3
ln -s ../manpages/p277 man3/sample_stroke.3
ln -s ../manpages/p278 man3/sample_stroke_3.3
ln -s ../manpages/p279 man3/sample_valuator.3
ln -s ../manpages/p280 man3/scale.3
ln -s ../manpages/p281 man3/scale_3.3
ln -s ../manpages/p282 man3/set_annotation_style.3
ln -s ../manpages/p283 man3/set_annotation_text_alignment.3
ln -s ../manpages/p284 man3/set_annotation_text_character_height.3
ln -s ../manpages/p285 man3/set_annotation_text_character_up_vector.3
ln -s ../manpages/p286 man3/set_annotation_text_path.3
ln -s ../manpages/p287 man3/set_back_interior_colour.3
ln -s ../manpages/p288 man3/set_back_interior_reflectance_equation.3
ln -s ../manpages/p289 man3/set_back_interior_shading_method.3
ln -s ../manpages/p290 man3/set_back_interior_style.3
ln -s ../manpages/p291 man3/set_back_interior_style_index.3
ln -s ../manpages/p292 man3/set_back_reflectance_properties.3
ln -s ../manpages/p293 man3/set_character_expansion_factor.3
ln -s ../manpages/p294 man3/set_character_height.3
ln -s ../manpages/p295 man3/set_character_spacing.3
ln -s ../manpages/p296 man3/set_character_up_vector.3
ln -s ../manpages/p297 man3/set_choice_mode.3
ln -s ../manpages/p298 man3/set_colour_mapping_index.3
ln -s ../manpages/p299 man3/set_colour_mapping_representation.3
ln -s ../manpages/p300 man3/set_colour_model.3
ln -s ../manpages/p301 man3/set_colour_representation.3
ln -s ../manpages/p302 man3/set_conflict_resolution.3
ln -s ../manpages/p303 man3/set_curve_approximation_criteria.3
ln -s ../manpages/p304 man3/set_depth_cue_index.3
ln -s ../manpages/p305 man3/set_depth_cue_representation.3
ln -s ../manpages/p306 man3/set_display_update_state.3
ln -s ../manpages/p307 man3/set_edge_colour.3
ln -s ../manpages/p308 man3/set_edge_colour_index.3
ln -s ../manpages/p309 man3/set_edge_flag.3
ln -s ../manpages/p310 man3/set_edge_index.3
ln -s ../manpages/p311 man3/set_edge_representation.3
ln -s ../manpages/p312 man3/set_edge_representation_plus.3
ln -s ../manpages/p313 man3/set_edgetype.3
ln -s ../manpages/p314 man3/set_edgewidth_scale_factor.3
ln -s ../manpages/p315 man3/set_edit_mode.3
ln -s ../manpages/p316 man3/set_element_pointer.3
ln -s ../manpages/p317 man3/set_element_pointer_at_label.3
ln -s ../manpages/p318 man3/set_error_handling.3
ln -s ../manpages/p319 man3/set_error_handling_mode.3
ln -s ../manpages/p320 man3/set_face_culling_mode.3
ln -s ../manpages/p321 man3/set_face_distinguishing_mode.3
ln -s ../manpages/p322 man3/set_global_transformation.3
ln -s ../manpages/p323 man3/set_global_transformation_3.3
ln -s ../manpages/p324 man3/set_highlighting_filter.3
ln -s ../manpages/p325 man3/set_hlhsr_identifier.3
ln -s ../manpages/p326 man3/set_hlhsr_mode.3
ln -s ../manpages/p327 man3/set_individual_asf.3
ln -s ../manpages/p328 man3/set_interior_colour.3
ln -s ../manpages/p329 man3/set_interior_colour_index.3
ln -s ../manpages/p330 man3/set_interior_index.3
ln -s ../manpages/p331 man3/set_interior_representation.3
ln -s ../manpages/p332 man3/set_interior_representation_plus.3
ln -s ../manpages/p333 man3/set_interior_shading_method.3
ln -s ../manpages/p334 man3/set_interior_style.3
ln -s ../manpages/p335 man3/set_interior_style_index.3
ln -s ../manpages/p336 man3/set_invisibility_filter.3
ln -s ../manpages/p337 man3/set_light_source_representation.3
ln -s ../manpages/p338 man3/set_light_source_state.3
ln -s ../manpages/p339 man3/set_linetype.3
ln -s ../manpages/p340 man3/set_linewidth_scale_factor.3
ln -s ../manpages/p341 man3/set_local_transformation.3
ln -s ../manpages/p342 man3/set_local_transformation_3.3
ln -s ../manpages/p343 man3/set_locator_mode.3
ln -s ../manpages/p344 man3/set_marker_size_scale_factor.3
ln -s ../manpages/p345 man3/set_marker_type.3
ln -s ../manpages/p346 man3/set_modelling_clipping_indicator.3
ln -s ../manpages/p347 man3/set_modelling_clipping_volume.3
ln -s ../manpages/p348 man3/set_modelling_clipping_volume_3.3
ln -s ../manpages/p349 man3/set_of_fill_area_set_3_with_data.3
ln -s ../manpages/p350 man3/set_parametric_surface_characteristics.3
ln -s ../manpages/p351 man3/set_pattern_reference_point.3
ln -s ../manpages/p352 man3/set_pattern_reference_point_and_vectors.3
ln -s ../manpages/p353 man3/set_pattern_representation.3
ln -s ../manpages/p354 man3/set_pattern_representation_plus.3
ln -s ../manpages/p355 man3/set_pattern_size.3
ln -s ../manpages/p356 man3/set_pick_filter.3
ln -s ../manpages/p357 man3/set_pick_identifier.3
ln -s ../manpages/p358 man3/set_pick_mode.3
ln -s ../manpages/p359 man3/set_polyline_colour.3
ln -s ../manpages/p360 man3/set_polyline_colour_index.3
ln -s ../manpages/p361 man3/set_polyline_index.3
ln -s ../manpages/p362 man3/set_polyline_representation.3
ln -s ../manpages/p363 man3/set_polyline_representation_plus.3
ln -s ../manpages/p364 man3/set_polyline_shading_method.3
ln -s ../manpages/p365 man3/set_polymarker_colour.3
ln -s ../manpages/p366 man3/set_polymarker_colour_index.3
ln -s ../manpages/p367 man3/set_polymarker_index.3
ln -s ../manpages/p368 man3/set_polymarker_representation.3
ln -s ../manpages/p369 man3/set_polymarker_representation_plus.3
ln -s ../manpages/p370 man3/set_reflectance_equation.3
ln -s ../manpages/p371 man3/set_reflectance_properties.3
ln -s ../manpages/p372 man3/set_rendering_colour_model.3
ln -s ../manpages/p373 man3/set_string_mode.3
ln -s ../manpages/p374 man3/set_stroke_mode.3
ln -s ../manpages/p375 man3/set_surface_approximation_criteria.3
ln -s ../manpages/p376 man3/set_text_alignment.3
ln -s ../manpages/p377 man3/set_text_colour.3
ln -s ../manpages/p378 man3/set_text_colour_index.3
ln -s ../manpages/p379 man3/set_text_font.3
ln -s ../manpages/p380 man3/set_text_index.3
ln -s ../manpages/p381 man3/set_text_path.3
ln -s ../manpages/p382 man3/set_text_precision.3
ln -s ../manpages/p383 man3/set_text_representation.3
ln -s ../manpages/p384 man3/set_text_representation_plus.3
ln -s ../manpages/p385 man3/set_valuator_mode.3
ln -s ../manpages/p386 man3/set_view_index.3
ln -s ../manpages/p387 man3/set_view_representation.3
ln -s ../manpages/p388 man3/set_view_representation_3.3
ln -s ../manpages/p389 man3/set_view_transformation_input_priority.3
ln -s ../manpages/p390 man3/set_workstation_viewport.3
ln -s ../manpages/p391 man3/set_workstation_viewport_3.3
ln -s ../manpages/p392 man3/set_workstation_window.3
ln -s ../manpages/p393 man3/set_workstation_window_3.3
ln -s ../manpages/p394 man3/text.3
ln -s ../manpages/p395 man3/text_3.3
ln -s ../manpages/p396 man3/transform_point.3
ln -s ../manpages/p397 man3/transform_point_3.3
ln -s ../manpages/p398 man3/translate.3
ln -s ../manpages/p399 man3/translate_3.3
ln -s ../manpages/p400 man3/triangle_strip_3_with_data.3
ln -s ../manpages/p401 man3/unpost_all_structures.3
ln -s ../manpages/p402 man3/unpost_structure.3
ln -s ../manpages/p403 man3/update_workstation.3
ln -s ../manpages/p404 man3/workstation_type_create.3
ln -s ../manpages/p405 man3/workstation_type_destroy.3
ln -s ../manpages/p406 man3/workstation_type_get.3
ln -s ../manpages/p407 man3/workstation_type_set.3

if [ ! -d man7 ]
then
	\mkdir man7
fi
yes | \rm man7/* 2>/dev/null

ln -s ../manpages/p408 man7/colour.7
ln -s ../manpages/p409 man7/phigs_description_table.7
ln -s ../manpages/p410 man7/phigs_traversal_state_list.7
ln -s ../manpages/p411 man7/phigs_workstation_description_table.7
